// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgresql

import (
	"time"

	"github.com/google/uuid"
)

type Endpoint struct {
	ID                     uuid.UUID
	UserID                 uuid.UUID
	Name                   string
	Token                  string
	NotificationEnabled    bool
	NotificationDisabledAt *time.Time
	CreatedAt              time.Time
}

type Notification struct {
	ID           uuid.UUID
	EndpointID   *uuid.UUID
	EndpointName string
	UserID       uuid.UUID
	Body         string
	Actions      []string
	Reaction     *string
	ReactionAt   *time.Time
	Status       *string
	ReadAt       *time.Time
	IsDeleted    bool
	CreatedAt    time.Time
}

type PushToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	P256dhKey string
	AuthKey   string
	Endpoint  string
	IsActive  bool
	CreatedAt time.Time
}

type User struct {
	ID          uuid.UUID
	Email       *string
	Guest       bool
	TermsAgreed bool
	CreatedAt   time.Time
	UpdatedAt   *time.Time
}
