// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifications.sql

package postgresql

import (
	"context"

	"github.com/google/uuid"
)

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (
    service_id,
    body
) VALUES (
    $1, $2
)
RETURNING id, service_id, body, is_read, read_at, is_deleted, created_at
`

type CreateNotificationParams struct {
	ServiceID uuid.UUID
	Body      string
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification, arg.ServiceID, arg.Body)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.Body,
		&i.IsRead,
		&i.ReadAt,
		&i.IsDeleted,
		&i.CreatedAt,
	)
	return i, err
}
