// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifications.sql

package postgresql

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createMuteNotification = `-- name: CreateMuteNotification :one
INSERT INTO notifications (
    endpoint_id,
    endpoint_name,
    user_id,
    body,
    status,
    read_at
)
SELECT 
    e.id, 
    e.name,
    $1,    
    $2,
    $3, 
    now()
FROM endpoints e
WHERE e.id = $4
RETURNING id, endpoint_id, endpoint_name, user_id, body, status, read_at, is_deleted, created_at
`

type CreateMuteNotificationParams struct {
	UserID uuid.UUID
	Body   string
	Status *string
	ID     uuid.UUID
}

func (q *Queries) CreateMuteNotification(ctx context.Context, arg CreateMuteNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createMuteNotification,
		arg.UserID,
		arg.Body,
		arg.Status,
		arg.ID,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.EndpointID,
		&i.EndpointName,
		&i.UserID,
		&i.Body,
		&i.Status,
		&i.ReadAt,
		&i.IsDeleted,
		&i.CreatedAt,
	)
	return i, err
}

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (
    endpoint_id,
    endpoint_name,
    user_id,
    body
)
SELECT 
    e.id, 
    e.name,
    $1,    
    $2    
FROM endpoints e
WHERE e.id = $3 
RETURNING id, endpoint_id, endpoint_name, user_id, body, status, read_at, is_deleted, created_at
`

type CreateNotificationParams struct {
	UserID uuid.UUID
	Body   string
	ID     uuid.UUID
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification, arg.UserID, arg.Body, arg.ID)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.EndpointID,
		&i.EndpointName,
		&i.UserID,
		&i.Body,
		&i.Status,
		&i.ReadAt,
		&i.IsDeleted,
		&i.CreatedAt,
	)
	return i, err
}

const findNotificationByUserID = `-- name: FindNotificationByUserID :many
SELECT 
    n.id, n.endpoint_id, n.endpoint_name, n.user_id, n.body, n.status, n.read_at, n.is_deleted, n.created_at,
    e.name as endpoint_name
FROM notifications n
JOIN endpoints e ON n.endpoint_id = e.id
WHERE n.user_id = $1
`

type FindNotificationByUserIDRow struct {
	ID             uuid.UUID
	EndpointID     *uuid.UUID
	EndpointName   string
	UserID         uuid.UUID
	Body           string
	Status         *string
	ReadAt         *time.Time
	IsDeleted      bool
	CreatedAt      time.Time
	EndpointName_2 string
}

func (q *Queries) FindNotificationByUserID(ctx context.Context, userID uuid.UUID) ([]FindNotificationByUserIDRow, error) {
	rows, err := q.db.Query(ctx, findNotificationByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindNotificationByUserIDRow
	for rows.Next() {
		var i FindNotificationByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.EndpointID,
			&i.EndpointName,
			&i.UserID,
			&i.Body,
			&i.Status,
			&i.ReadAt,
			&i.IsDeleted,
			&i.CreatedAt,
			&i.EndpointName_2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNotificationsWithCursor = `-- name: GetNotificationsWithCursor :many
SELECT 
    n.id,
    n.endpoint_id,
    n.user_id,
    n.body,
    n.status,
    n.read_at,
    n.created_at,
    n.endpoint_name
FROM notifications n
WHERE n.user_id = $1 
  AND n.is_deleted = false
  AND ($3::uuid IS NULL OR n.endpoint_id = $3)
  AND ($4::uuid IS NULL OR n.id < $4)
ORDER BY n.id DESC
LIMIT $2
`

type GetNotificationsWithCursorParams struct {
	UserID     uuid.UUID
	Limit      int32
	EndpointID *uuid.UUID
	LastID     *uuid.UUID
}

type GetNotificationsWithCursorRow struct {
	ID           uuid.UUID
	EndpointID   *uuid.UUID
	UserID       uuid.UUID
	Body         string
	Status       *string
	ReadAt       *time.Time
	CreatedAt    time.Time
	EndpointName string
}

func (q *Queries) GetNotificationsWithCursor(ctx context.Context, arg GetNotificationsWithCursorParams) ([]GetNotificationsWithCursorRow, error) {
	rows, err := q.db.Query(ctx, getNotificationsWithCursor,
		arg.UserID,
		arg.Limit,
		arg.EndpointID,
		arg.LastID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetNotificationsWithCursorRow
	for rows.Next() {
		var i GetNotificationsWithCursorRow
		if err := rows.Scan(
			&i.ID,
			&i.EndpointID,
			&i.UserID,
			&i.Body,
			&i.Status,
			&i.ReadAt,
			&i.CreatedAt,
			&i.EndpointName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDeleteNotificationByID = `-- name: MarkDeleteNotificationByID :exec
UPDATE notifications
SET is_deleted = true
WHERE user_id = $1
  AND id = $2
`

type MarkDeleteNotificationByIDParams struct {
	UserID uuid.UUID
	ID     uuid.UUID
}

func (q *Queries) MarkDeleteNotificationByID(ctx context.Context, arg MarkDeleteNotificationByIDParams) error {
	_, err := q.db.Exec(ctx, markDeleteNotificationByID, arg.UserID, arg.ID)
	return err
}

const markNotificationsAsReadBefore = `-- name: MarkNotificationsAsReadBefore :exec
UPDATE notifications
SET read_at = now()
WHERE user_id = $1 
  AND id >= $2
`

type MarkNotificationsAsReadBeforeParams struct {
	UserID uuid.UUID
	ID     uuid.UUID
}

func (q *Queries) MarkNotificationsAsReadBefore(ctx context.Context, arg MarkNotificationsAsReadBeforeParams) error {
	_, err := q.db.Exec(ctx, markNotificationsAsReadBefore, arg.UserID, arg.ID)
	return err
}

const updateStatusNotification = `-- name: UpdateStatusNotification :exec
UPDATE notifications
SET status = $2
WHERE id = $1
`

type UpdateStatusNotificationParams struct {
	ID     uuid.UUID
	Status *string
}

func (q *Queries) UpdateStatusNotification(ctx context.Context, arg UpdateStatusNotificationParams) error {
	_, err := q.db.Exec(ctx, updateStatusNotification, arg.ID, arg.Status)
	return err
}
