// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: push_token.sql

package postgresql

import (
	"context"

	"github.com/google/uuid"
)

const upsertToken = `-- name: UpsertToken :one
INSERT INTO push_tokens (
    user_id,
    p256dh_key,
    auth_key,
    is_active
)
VALUES ($1, $2, $3, true)
ON CONFLICT (user_id, p256dh_key, auth_key)
DO UPDATE SET
    is_active = true
RETURNING user_id
`

type UpsertTokenParams struct {
	UserID    uuid.UUID
	P256dhKey string
	AuthKey   string
}

func (q *Queries) UpsertToken(ctx context.Context, arg UpsertTokenParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, upsertToken, arg.UserID, arg.P256dhKey, arg.AuthKey)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}
