// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: push_token.sql

package postgresql

import (
	"context"

	"github.com/google/uuid"
)

const deactivatePushToken = `-- name: DeactivatePushToken :exec
UPDATE push_tokens
SET is_active = false
WHERE endpoint = $1
`

func (q *Queries) DeactivatePushToken(ctx context.Context, endpoint string) error {
	_, err := q.db.Exec(ctx, deactivatePushToken, endpoint)
	return err
}

const deleteToken = `-- name: DeleteToken :exec
DELETE FROM push_tokens
WHERE endpoint = $1 
    AND p256dh_key = $2 
    AND auth_key = $3
`

type DeleteTokenParams struct {
	Endpoint  string
	P256dhKey string
	AuthKey   string
}

func (q *Queries) DeleteToken(ctx context.Context, arg DeleteTokenParams) error {
	_, err := q.db.Exec(ctx, deleteToken, arg.Endpoint, arg.P256dhKey, arg.AuthKey)
	return err
}

const findTokenByEndpoint = `-- name: FindTokenByEndpoint :one
SELECT id, user_id, p256dh_key, auth_key, endpoint, is_active, created_at FROM push_tokens
WHERE endpoint = $1
`

func (q *Queries) FindTokenByEndpoint(ctx context.Context, endpoint string) (PushToken, error) {
	row := q.db.QueryRow(ctx, findTokenByEndpoint, endpoint)
	var i PushToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.P256dhKey,
		&i.AuthKey,
		&i.Endpoint,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const findTokenByUserID = `-- name: FindTokenByUserID :many
SELECT id, user_id, p256dh_key, auth_key, endpoint, is_active, created_at FROM push_tokens
WHERE user_id = $1 AND is_active = true
`

func (q *Queries) FindTokenByUserID(ctx context.Context, userID uuid.UUID) ([]PushToken, error) {
	rows, err := q.db.Query(ctx, findTokenByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PushToken
	for rows.Next() {
		var i PushToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.P256dhKey,
			&i.AuthKey,
			&i.Endpoint,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertToken = `-- name: UpsertToken :one
INSERT INTO push_tokens (
    user_id,
    p256dh_key,
    auth_key,
    endpoint
)
VALUES ($1, $2, $3, $4)
ON CONFLICT (p256dh_key, auth_key, endpoint)
DO UPDATE SET
    is_active = true,
    user_id = EXCLUDED.user_id
RETURNING user_id
`

type UpsertTokenParams struct {
	UserID    uuid.UUID
	P256dhKey string
	AuthKey   string
	Endpoint  string
}

func (q *Queries) UpsertToken(ctx context.Context, arg UpsertTokenParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, upsertToken,
		arg.UserID,
		arg.P256dhKey,
		arg.AuthKey,
		arg.Endpoint,
	)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}
