// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package postgresql

import (
	"context"

	"github.com/google/uuid"
)

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const findUserById = `-- name: FindUserById :one
SELECT id, email, provider, provider_id, guest, terms_agreed, created_at, updated_at
FROM users
WHERE id = $1
`

func (q *Queries) FindUserById(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, findUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Provider,
		&i.ProviderID,
		&i.Guest,
		&i.TermsAgreed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertGuestUser = `-- name: InsertGuestUser :one
INSERT INTO users (guest, terms_agreed)
VALUES (true, true)
RETURNING id, email, provider, provider_id, guest, terms_agreed, created_at, updated_at
`

func (q *Queries) InsertGuestUser(ctx context.Context) (User, error) {
	row := q.db.QueryRow(ctx, insertGuestUser)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Provider,
		&i.ProviderID,
		&i.Guest,
		&i.TermsAgreed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserTermsAgreed = `-- name: UpdateUserTermsAgreed :exec
UPDATE users
SET terms_agreed = true
WHERE id = $1
`

func (q *Queries) UpdateUserTermsAgreed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateUserTermsAgreed, id)
	return err
}

const upsertUserByProvider = `-- name: UpsertUserByProvider :one
INSERT INTO users (provider, provider_id, email, updated_at)
VALUES ($1, $2, $3, now())
ON CONFLICT (provider, provider_id)
DO UPDATE SET
    email = COALESCE(EXCLUDED.email, users.email),
    updated_at = EXCLUDED.updated_at
RETURNING id, email, provider, provider_id, guest, terms_agreed, created_at, updated_at
`

type UpsertUserByProviderParams struct {
	Provider   *string
	ProviderID *string
	Email      *string
}

func (q *Queries) UpsertUserByProvider(ctx context.Context, arg UpsertUserByProviderParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUserByProvider, arg.Provider, arg.ProviderID, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Provider,
		&i.ProviderID,
		&i.Guest,
		&i.TermsAgreed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
